### ISSUE TITLE
Implement `round()`

### ISSUE THREAD

**Issue by daxpedda** [823984418/const_soft_float#4]
I found myself needing `round()` lately, see https://doc.rust-lang.org/std/primitive.f64.html#method.round.

A quick glance at `compiler_builtins` shows that they don't actually offer it either.

**Comment by knickish** [comment]
Sure, will see what I can do.

**Comment by zRedShift** [comment]
I suggest looking at the Berkeley SoftFloat [implementation](https://github.com/ucb-bar/berkeley-softfloat-3/blob/master/source/s_roundMToI64.c).

Edit: Although I suppose basing it on the rust [libm](https://github.com/rust-lang/libm/blob/master/src/math/trunc.rs) is even [better](https://github.com/rust-lang/libm/blob/master/src/math/round.rs)...

**Comment by knickish** [comment]
It's in CI now, but should be all good. Had to add `trunc` and `copysign` also to match the `libm` implementation.

**Comment by daxpedda** [comment]
Wow, that was fast.
Amazing work, thank you!
